### ISSUE TITLE
Hey there, I wanna know how you uploaded such a big file on Github?

### ISSUE THREAD

**Issue by MauryaRitesh** [zemirco/sf-city-lots-json#1]
Hey there, I wanna know how you uploaded such a big file on Github?
I'm trying for a while to upload big files on GitHub, can you help me to solve this issue?

**Comment by runebaas** [comment]
The file was uploaded 6 years ago, before [github changed the max file size in 2013](https://blog.github.com/2013-06-18-new-file-size-limits/), you can however use [git lfs](https://git-lfs.github.com) to upload large files  ([limited to 2gb on github](https://github.com/git-lfs/git-lfs/issues/1073))

**Comment by MauryaRitesh** [comment]
Thanks, but still I want about 5GB of storage space!
